"""add filial de origem e destino na tabela CI

Revision ID: 2a068c36e005
Revises: bc36f3531bae
Create Date: 2024-01-31 16:08:44.911573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a068c36e005'
down_revision: Union[str, None] = 'bc36f3531bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('correspondencia_interna', sa.Column('cod_filial_origem', sa.Integer(), nullable=False))
    op.add_column('correspondencia_interna', sa.Column('cod_filial_destino', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'correspondencia_interna', 'filial', ['cod_filial_destino'], ['cod_filial'])
    op.create_foreign_key(None, 'correspondencia_interna', 'filial', ['cod_filial_origem'], ['cod_filial'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'correspondencia_interna', type_='foreignkey')
    op.drop_constraint(None, 'correspondencia_interna', type_='foreignkey')
    op.drop_column('correspondencia_interna', 'cod_filial_destino')
    op.drop_column('correspondencia_interna', 'cod_filial_origem')
    # ### end Alembic commands ###
