"""add data_criacao e data_entrega tabela CI

Revision ID: 3502dd6b1172
Revises: bb35f624a4ab
Create Date: 2024-02-05 09:29:40.084113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3502dd6b1172'
down_revision: Union[str, None] = 'bb35f624a4ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('correspondencia_interna', sa.Column('data_criacao', sa.DateTime(), nullable=False))
    op.add_column('correspondencia_interna', sa.Column('data_entrega', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('correspondencia_interna', 'data_entrega')
    op.drop_column('correspondencia_interna', 'data_criacao')
    # ### end Alembic commands ###
