"""First revision

Revision ID: bc36f3531bae
Revises: 
Create Date: 2024-01-31 15:18:31.627539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc36f3531bae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cod_filial', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.Integer(), nullable=False),
    sa.Column('uf', sa.String(), nullable=False),
    sa.Column('cep', sa.Integer(), nullable=False),
    sa.Column('rua', sa.String(), nullable=False),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_filial')
    )
    op.create_table('tipo_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_status', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_status')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_matricula', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('cod_filial', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cod_filial'], ['filial.cod_filial'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_matricula')
    )
    op.create_table('correspondencia_interna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_ci', sa.Integer(), nullable=False),
    sa.Column('user_id_remetente', sa.Integer(), nullable=False),
    sa.Column('user_id_destinatario', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['status'], ['tipo_status.cod_status'], ),
    sa.ForeignKeyConstraint(['user_id_destinatario'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id_remetente'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_ci')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('correspondencia_interna')
    op.drop_table('user')
    op.drop_table('tipo_status')
    op.drop_table('filial')
    # ### end Alembic commands ###
